version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: db_Nix_Trainee
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nix_db
      - DATABASE_HOST=localhost:8081
    ports:
      - '8081:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
   driver: local